### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mpconnolly** [dacarlin/fitter#12]
Tried inputting copied data from Gen5 and got an internal server error. Then tried converting from scientific notation (E^x) to a plain decimal in case that was the issue but got the same error.

**Comment by dacarlin** [comment]
Thanks for testing it out. Turns out Matplotlib was unhappy with the degree symbol ˚ in some of the plotting code: 

```
ValueError: matplotlib display text must have all code points < 128 or use Unicode strings
```

I fixed it
